### ISSUE TITLE
Is the Per-File DAX Option in Linux 5.17 useful to this driver in any way?

### ISSUE THREAD

**Issue by volkertb** [jaylogue/retro-fuse#3]
Hi. 

First of all, thanks for sharing this useful project with the world. :slightly_smiling_face:

(I'm creating an issue for this, since [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) is currently not enabled for this project. You can turn this issue into a discussion once you enable that feature for this repo, should you so choose.)

So I read an article on Phoronix about [a "Per-File DAX" performance improvement being introduced in FUSE in the upcoming Linux kernel version 5.17](https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.17-FUSE-Per-inode-DAX).

Two things I'm wondering, with my limited understanding of this feature:

- Would this enhancement benefit the retro-fuse driver in any way?
- Would this require modifications in the retro-fuse driver code in order to take advantage of it, or do we basically get it for free?

My apologies if these questions come off as completely clueless.

**Comment by jaylogue** [comment]
No apologies necessary.  I wasn't aware of the DAX enhancements myself, so at a minimum you helped me learn something new!

There doesn't appear to be much information on DAX out there.  But based on a quick review of the topic, I don't think it has much bearing on retro-fuse, or other fuse filesystems like it.  DAX appears to provide a way to map cache pages from an underlying VM host OS directly into a guest OS, thereby bypassing the guest's page cache.  It is true that, when using retro-fuse, there are in fact two pages caches in play--the standard Linux page cache in the host OS and the ancient Unix page cache in the retro-fuse process.  However, as far as I can tell, DAX does not appear to provide a way to map these caches together.  And if it were possible to do, I expect it would take quite a bit of code modification to make work.

That brings up a related point about retro-fuse: when implementing it I specifically avoided any modifications to the ancient code that were intended solely to improve performance. I figured that, on modern hardware, the code would be plenty fast enough for use by casual retro-computing enthusiasts.

Thanks for the pointer to the Discussions feature; I will look into it.  And thanks for reaching out.

**Comment by volkertb** [comment]
And thanks for the detailed explanation. I guess we can close this issue then. :slightly_smiling_face:
